In [5]:
import numpy as np
import pandas as pd
import sklearn as sk
import random

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_regression
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import metrics, datasets
from sklearn.metrics import classification_report
from sklearn import tree
#from sklearn.learning_curve import learning_curve
from sklearn import metrics
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.externals import joblib

In [6]:
data = pd.read_csv("new1.csv")
X = data.drop(['gross','company','director','name','released','star','writer'],axis=1)

l1=['Adventure', 'Comedy', 'Action', 'Drama', 'Crime', 'Thriller', 'Horror', 'Animation', 'Biography', 'Sci-Fi', 'Musical', 'Family', 'Fantasy', 'Mystery', 'War', 'Romance', 'Western']
l2=['Argentina','Australia','Belgium','Canada','China','Denmark','France','Germany','Hong Kong','Hungary','Iran','Isreal','Italy','Japan','Netherlands','New Zealand','Peru','South Africa','Spain','Sweden','Switzerland','UK','USA','West Germany']
l3=['R','PG-13','PG','UNRATED','G','NC-17','TV-PG','TV-MA','B','B15','TV-14']
for i in range(X['genre'].size):
    for j in range(len(l1)):
         if(X['genre'][i]==l1[j]):
                X['genre'][i]=j
for i in range(X['country'][i].size()):
    for j in range(len(l2)):
         if(X['country'][i]==l2[i]):
                X['country'][i]=j  
for i in range(X['rating'][i].size):
    for j in range(len(l3)):
         if(X['rating'][i]==l3[i]):
                X['rating'][i]=j
         else:
         X['genre'][i]=3
Y=data['gross']        
Y = Y.values.reshape(-1, 1)##convert 1 col to 2d matrix with replace
for i in range(Y.size):
    if(Y[i]<33497828.61):
        Y[i]=1
    else:
        Y[i]=2

SyntaxError: EOL while scanning string literal (<ipython-input-6-5908d7f9daf9>, line 10)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.8, test_size=0.2, shuffle=True)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

In [ ]:
##LOGISTIC REGRESSION MODEL
lr = LogisticRegression(C=1e5, solver='newton-cg')
lr.fit(x_train, y_train)
y_pred_train = lr.predict(x_train)
y_pred_test = lr.predict(x_test)

print(lr)
print('Coefficients = ', lr.coef_)
print('Intercept = ', lr.intercept_)

print('Training Accuracy {}'.format(lr.score(x_train, y_train)))
print('Training Confusion = {}'.format(metrics.confusion_matrix(y_pred_train, y_train)))
print(classification_report(y_train, y_pred_train))
print('========================================================')
print('Test Accuracy {}'.format(lr.score(x_test, y_test)))
print('Test Confusion = {}'.format(metrics.confusion_matrix(y_pred_test, y_test)))
print(classification_report(y_test, y_pred_test))
#saving the weights
joblib.dump(lr,'lrweight.joblib')

In [17]:
##DECISION TREE MODEL
clfdt = tree.DecisionTreeClassifier(criterion='gini', splitter='best')
clfdt.fit(x_train, y_train)
y_pred_train = clfdt.predict(x_train)
y_pred_test = clfdt.predict(x_test)
print(clfdt)

dot_data = tree.export_graphviz(clfdt, out_file=None, feature_names=['sepal_length','sepal_width','petal_length','petal_width'],class_names=['setosa','versicolor','virginica'], filled=True, rounded=True, special_characters=True)
graph = graphviz.Source(dot_data)
graph.render("movie-train")
print('Training Accuracy {}'.format(clfdt.score(x_train, y_train)))
print('Training Confusion = {}'.format(metrics.confusion_matrix(y_pred_train, y_train, [0,1,2])))
print(classification_report(y_train, y_pred_train))
print('========================================================')
print('Test Accuracy {}'.format(clfdt.score(x_test, y_test)))
print('Test Confusion = {}'.format(metrics.confusion_matrix(y_pred_test, y_test, [0,1,2])))
print(classification_report(y_test, y_pred_test))
#saving the weights
joblib.dump(clfdt,'dtweight.joblib')

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')


ValueError: Length of feature_names, 4 does not match number of features, 7

In [18]:
##SUPPORT VECTOR MACHINE MODEL
svc = LinearSVC(max_iter=20)
svc.fit(x_train, y_train)
y_pred_train = svc.predict(x_train)
y_pred_test = svc.predict(x_test)

print(svc)

print('Training Accuracy {}'.format(svc.score(x_train, y_train)))
print('Training Confusion = {}'.format(metrics.confusion_matrix(y_pred_train, y_train, [0,1,2])))
print(classification_report(y_train, y_pred_train))
print('========================================================')
print('Test Accuracy {}'.format(svc.score(x_test, y_test)))
print('Test Confusion = {}'.format(metrics.confusion_matrix(y_pred_test, y_test, [0,1,2])))
print(classification_report(y_test, y_pred_test))
#saving the weights
joblib.dump(svc,'svcwt.joblib')

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=20,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
Training Accuracy 0.7005131964809385
Training Confusion = [[   0    0    0]
 [   0 3753 1510]
 [   0  124   69]]
              precision    recall  f1-score   support

           1       0.71      0.97      0.82      3877
           2       0.36      0.04      0.08      1579

   micro avg       0.70      0.70      0.70      5456
   macro avg       0.54      0.51      0.45      5456
weighted avg       0.61      0.70      0.61      5456

Test Accuracy 0.6854838709677419
Test Confusion = [[  0   0   0]
 [  0 917 392]
 [  0  37  18]]
              precision    recall  f1-score   support

           1       0.70      0.96      0.81       954
           2       0.33      0.04      0.08       410

   micro avg       0.69      0.69      0.69      1364
   macro avg       0.51      0.50

/Users/Swayamprava/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/Swayamprava/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


['svcwt.joblib']

In [19]:
##NEURAL NETWORK MODEL
NN=MLPClassifier(hidden_layer_sizes=(2,2), activation='relu',solver='adam',alpha=0.0001).fit(x_train,y_train)
y_pred_train = NN.predict(x_train)
y_pred_test = NN.predict(x_test)
print(NN)
print('Training Accuracy {}'.format(NN.score(x_train, y_train)))
print(classification_report(y_train, y_pred_train))
print('Test Accuracy {}'.format(svc.score(x_test, y_test)))
#saving the weights
joblib.dump(NN,'nnwt.joblib')

/Users/Swayamprava/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(2, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)
Training Accuracy 0.7105938416422287
              precision    recall  f1-score   support

           1       0.71      1.00      0.83      3877
           2       0.00      0.00      0.00      1579

   micro avg       0.71      0.71      0.71      5456
   macro avg       0.36      0.50      0.42      5456
weighted avg       0.50      0.71      0.59      5456

Test Accuracy 0.6854838709677419


/Users/Swayamprava/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


['nnwt.joblib']

In [20]:
##RANDOMFORREST CLASSIFIER
rf = RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1,criterion='gini').fit(x_train,y_train)
print("TRAIN ACCURACY",rf.score(x_train,y_train))
print("TEST ACCURACY",rf.score(x_test,y_test))
#print(accuracy_score(y_train, , normalize=True, sample_weight=None))
joblib.dump(rf,'rfwt.joblib')



TRAIN ACCURACY 0.8577712609970675
TEST ACCURACY 0.8357771260997068


/Users/Swayamprava/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


['rfwt.joblib']